# Generated by Django 6.1 on 2026-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeenote_leaverequest_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave'), ('late', 'Late (> 10:00 AM)'), ('lop', 'Loss of Pay (LOP)'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
    ]
