# Generated by Django 6.1 on 2026-08-25 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=30)),
                ('personal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='Not Specified', max_length=20)),
                ('marital_status', models.CharField(default='Single', max_length=20)),
                ('blood_group', models.CharField(default='O+', max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, default='Emergency Contact', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='+91 98765 00000', max_length=30)),
                ('emergency_relation', models.CharField(blank=True, default='Family', max_length=50)),
                ('current_address', models.TextField(blank=True, default='Tech Park View, Bangalore, Karnataka, India')),
                ('permanent_address', models.TextField(blank=True, default='Tech Park View, Bangalore, Karnataka, India')),
                ('department', models.CharField(default='Engineering', max_length=100)),
                ('designation', models.CharField(default='Software Engineer', max_length=100)),
                ('work_location', models.CharField(default='Headquarters (Bangalore)', max_length=100)),
                ('employment_type', models.CharField(default='Full-Time Permanent', max_length=50)),
                ('probation_status', models.CharField(default='Confirmed', max_length=50)),
                ('reporting_manager', models.CharField(default='Kavitha Ramesh (CTO)', max_length=100)),
                ('work_shift', models.CharField(default='General Shift (09:30 AM - 06:30 PM)', max_length=100)),
                ('bank_name', models.CharField(default='HDFC Bank', max_length=100)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(default='50100234567890', max_length=50)),
                ('ifsc_code', models.CharField(default='HDFC0001234', max_length=30)),
                ('branch_name', models.CharField(default='Electronic City Branch', max_length=100)),
                ('pan_number', models.CharField(default='ABCDE1234F', max_length=30)),
                ('uan_number', models.CharField(default='100987654321', max_length=30)),
                ('pf_number', models.CharField(default='KN/BNG/12345/67890', max_length=50)),
                ('payment_mode', models.CharField(default='Direct Bank Transfer (NEFT/RTGS)', max_length=50)),
                ('ctc_annual', models.DecimalField(decimal_places=2, default=1200000.0, max_digits=12)),
                ('basic_monthly', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('hra_monthly', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('special_allowance_monthly', models.DecimalField(decimal_places=2, default=20000.0, max_digits=10)),
                ('conveyance_monthly', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('pf_deduction_monthly', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10)),
                ('tax_deduction_monthly', models.DecimalField(decimal_places=2, default=4000.0, max_digits=10)),
                ('increment_history', models.JSONField(blank=True, default=list)),
                ('experience_history', models.JSONField(blank=True, default=list)),
                ('education_history', models.JSONField(blank=True, default=list)),
                ('documents_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
