# Generated by Django 6.1 on 2026-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
