# Generated by Django 6.1 on 2026-08-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permissionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeNote',
        ),
    ]
