# Generated by Django 6.1 on 2026-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_employeenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='team',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('hr_executive', 'HR Executive'), ('manager', 'Manager'), ('development', 'Development'), ('finance', 'Finance'), ('support', 'Support')], default='development', max_length=50),
        ),
    ]
