# Generated by Django 6.1 on 2026-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employeeprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='assigned_by',
            field=models.CharField(blank=True, default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='project',
            field=models.CharField(default='HRMS Portal', max_length=100),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='task_type',
            field=models.CharField(choices=[('dev', 'Development'), ('support', 'Support'), ('design', 'Design'), ('qa', 'QA / Testing'), ('hr', 'HR & Admin'), ('finance', 'Finance')], default='dev', max_length=30),
        ),
    ]
