# Generated by Django 6.1 on 2026-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dailytask_assigned_by_dailytask_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='assigned_by',
            field=models.CharField(blank=True, default='Admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='project',
            field=models.CharField(blank=True, default='HRMS Portal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('dev', 'Development'), ('support', 'Support'), ('design', 'Design'), ('qa', 'QA / Testing'), ('hr', 'HR & Admin'), ('finance', 'Finance')], default='dev', max_length=30, null=True),
        ),
    ]
