# Generated by Django 6.1 on 2026-08-30 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_dailytask_assigned_by_alter_dailytask_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(default='System Administrator', max_length=100)),
                ('department', models.CharField(default='Engineering', max_length=100)),
                ('designation', models.CharField(default='Software Engineer', max_length=100)),
                ('review_cycle', models.CharField(default='Q3 2026 - Annual Appraisal', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('status', models.CharField(default='Excellent', max_length=50)),
                ('comments', models.TextField(blank=True, default='')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-review_date'],
            },
        ),
    ]
